/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author nisit
 */
public class Interfaz_Nueva_Receta extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Nueva_Receta
     */
    public Interfaz_Nueva_Receta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cantidad.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(195, 161, 50, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 224.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(301, 162, 30, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 227.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(263, 379, 90, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingredientes.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(52, 142, 70, 12);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nombre.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(52, 62, 50, 10);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Porciones.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(52, 100, 60, 10);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Procedimiento.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(52, 250, 90, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 97.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(261, 162, 40, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vector 1.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 158, 20, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 100.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(51, 156, 300, 90);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 111.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 113, 40, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 184.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(51, 274, 300, 90);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 99.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(47, 75, 200, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tipo.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(125, 100, 30, 12);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barrita.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(113, 113, 131, 20);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 47.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(37, 9, 150, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 200.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(343, 35, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 96.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(27, 24, 350, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 95.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 394, 428);

        jPanel2.setLayout(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cantidad.png"))); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(195, 161, 50, 16);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 224.png"))); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(301, 162, 30, 14);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 227.png"))); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(263, 379, 90, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingredientes.png"))); // NOI18N
        jPanel2.add(jLabel23);
        jLabel23.setBounds(52, 142, 70, 12);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nombre.png"))); // NOI18N
        jPanel2.add(jLabel24);
        jLabel24.setBounds(52, 62, 50, 10);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Porciones.png"))); // NOI18N
        jPanel2.add(jLabel25);
        jLabel25.setBounds(52, 100, 60, 10);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Procedimiento.png"))); // NOI18N
        jPanel2.add(jLabel26);
        jLabel26.setBounds(52, 250, 90, 20);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 97.png"))); // NOI18N
        jPanel2.add(jLabel27);
        jLabel27.setBounds(261, 162, 40, 14);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vector 1.png"))); // NOI18N
        jPanel2.add(jLabel28);
        jLabel28.setBounds(60, 158, 20, 20);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 100.png"))); // NOI18N
        jPanel2.add(jLabel29);
        jLabel29.setBounds(51, 156, 300, 90);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 111.png"))); // NOI18N
        jPanel2.add(jLabel30);
        jLabel30.setBounds(50, 113, 40, 20);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 184.png"))); // NOI18N
        jPanel2.add(jLabel31);
        jLabel31.setBounds(51, 274, 300, 90);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 99.png"))); // NOI18N
        jPanel2.add(jLabel32);
        jLabel32.setBounds(47, 75, 200, 20);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tipo.png"))); // NOI18N
        jPanel2.add(jLabel33);
        jLabel33.setBounds(125, 100, 30, 12);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barrita.png"))); // NOI18N
        jPanel2.add(jLabel34);
        jLabel34.setBounds(113, 113, 131, 20);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 47.png"))); // NOI18N
        jPanel2.add(jLabel35);
        jLabel35.setBounds(37, 9, 150, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 200.png"))); // NOI18N
        jPanel2.add(jLabel36);
        jLabel36.setBounds(343, 35, 20, 20);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 96.png"))); // NOI18N
        jPanel2.add(jLabel37);
        jLabel37.setBounds(27, 24, 350, 370);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 95.png"))); // NOI18N
        jPanel2.add(jLabel38);
        jLabel38.setBounds(0, 0, 394, 428);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Nueva_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Nueva_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Nueva_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Nueva_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Nueva_Receta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
