/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author nisit
 */
public class Interfaz_Ingredientes extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Ingredientes
     */
    public Interfaz_Ingredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_X = new javax.swing.JLabel();
        Lbl_Cantidad_Verde_Oscuro = new javax.swing.JLabel();
        Lbl_Rectangulo_Ingrediente = new javax.swing.JLabel();
        Lbl_Vegetales = new javax.swing.JLabel();
        Lbl_Cuadrado_Vegetales = new javax.swing.JLabel();
        Lbl_Aceptar = new javax.swing.JLabel();
        Lbl_Fecha_Caducidad = new javax.swing.JLabel();
        Lbl_Tipo = new javax.swing.JLabel();
        Lbl_Cantidad_Opcion = new javax.swing.JLabel();
        Lbl_Cantidad_Texto = new javax.swing.JLabel();
        Lbl_Cantidad = new javax.swing.JLabel();
        Lbl_Rectangulo_Gris = new javax.swing.JLabel();
        Lbl_Fecha_Caducidad_Texto = new javax.swing.JLabel();
        Lbl_Tipo_Opcion = new javax.swing.JLabel();
        Lbl_Rectangulo_Claro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(111, 150, 98));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_X.png"))); // NOI18N
        Lbl_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_XMouseClicked(evt);
            }
        });
        jPanel1.add(Lbl_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 34, -1, -1));

        Lbl_Cantidad_Verde_Oscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Cantidad_Rectangulo_Oscuro.png"))); // NOI18N
        jPanel1.add(Lbl_Cantidad_Verde_Oscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 42, -1, -1));

        Lbl_Rectangulo_Ingrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Rectangulo_Ingrediente.png"))); // NOI18N
        jPanel1.add(Lbl_Rectangulo_Ingrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 18, -1, -1));

        Lbl_Vegetales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Vegetales.png"))); // NOI18N
        jPanel1.add(Lbl_Vegetales, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 70, -1, -1));

        Lbl_Cuadrado_Vegetales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Vegetales_Cuadrado.png"))); // NOI18N
        jPanel1.add(Lbl_Cuadrado_Vegetales, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 66, -1, -1));

        Lbl_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Aceptar.png"))); // NOI18N
        jPanel1.add(Lbl_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 124, -1, -1));

        Lbl_Fecha_Caducidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Fecha_Caducidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Fecha_Caducidad.png"))); // NOI18N
        jPanel1.add(Lbl_Fecha_Caducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 73, 102, 14));

        Lbl_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Tipo.png"))); // NOI18N
        jPanel1.add(Lbl_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 95, 79, 20));

        Lbl_Cantidad_Opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Cantidad_Opcion.png"))); // NOI18N
        jPanel1.add(Lbl_Cantidad_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 74, -1, -1));

        Lbl_Cantidad_Texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Cantidad_Texto.png"))); // NOI18N
        jPanel1.add(Lbl_Cantidad_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 73, -1, -1));

        Lbl_Cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Cantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Cantidad.png"))); // NOI18N
        jPanel1.add(Lbl_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 58, 78, 19));

        Lbl_Rectangulo_Gris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Rectangulo_Gris.png"))); // NOI18N
        jPanel1.add(Lbl_Rectangulo_Gris, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 73, -1, -1));

        Lbl_Fecha_Caducidad_Texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Fecha_Caducidad_Texto.png"))); // NOI18N
        jPanel1.add(Lbl_Fecha_Caducidad_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        Lbl_Tipo_Opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Tipo_Opcion.png"))); // NOI18N
        jPanel1.add(Lbl_Tipo_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 94, -1, -1));

        Lbl_Rectangulo_Claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Rectangulo_Claro.png"))); // NOI18N
        jPanel1.add(Lbl_Rectangulo_Claro, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Lbl_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_XMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Lbl_XMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Ingredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Aceptar;
    private javax.swing.JLabel Lbl_Cantidad;
    private javax.swing.JLabel Lbl_Cantidad_Opcion;
    private javax.swing.JLabel Lbl_Cantidad_Texto;
    private javax.swing.JLabel Lbl_Cantidad_Verde_Oscuro;
    private javax.swing.JLabel Lbl_Cuadrado_Vegetales;
    private javax.swing.JLabel Lbl_Fecha_Caducidad;
    private javax.swing.JLabel Lbl_Fecha_Caducidad_Texto;
    private javax.swing.JLabel Lbl_Rectangulo_Claro;
    private javax.swing.JLabel Lbl_Rectangulo_Gris;
    private javax.swing.JLabel Lbl_Rectangulo_Ingrediente;
    private javax.swing.JLabel Lbl_Tipo;
    private javax.swing.JLabel Lbl_Tipo_Opcion;
    private javax.swing.JLabel Lbl_Vegetales;
    private javax.swing.JLabel Lbl_X;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
