/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author miagu
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

import javax.swing.JButton;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import raven.scroll.win11.ScrollBarWin11UI;
public class Interfaz_Refrigerador extends javax.swing.JFrame {

    /**
     * Creates new form Recetario
     */
    public Interfaz_Refrigerador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        scrollPaneWin111 = new raven.scroll.win11.ScrollPaneWin11();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(111, 150, 98));
        jPanel1.setMaximumSize(new java.awt.Dimension(402, 443));
        jPanel1.setMinimumSize(new java.awt.Dimension(402, 443));
        jPanel1.setPreferredSize(new java.awt.Dimension(402, 443));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneWin111.setBackground(new java.awt.Color(233, 255, 206));
        scrollPaneWin111.setBorder(null);

        listPanel.setBackground(new java.awt.Color(233, 255, 206));

        for (int i = 1; i <= 10; i++)
        listPanel.addPanel(new Interfaces.Panel_Opcion(0), 5);
        JButton btnAdd = new JButton("Add");
        btnAdd.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent paramActionEvent)
                {
                    listPanel.addPanel(Interfaces.Panel_Lista.getRandomJPanel(), 50);
                }
            });
            JButton btnRemove = new JButton("Remove");
            btnRemove.addActionListener(new ActionListener()
                {
                    public void actionPerformed(ActionEvent paramActionEvent)
                    {
                        listPanel.removePanel(0);
                    }
                });

                scrollPaneWin111.setViewportView(listPanel);

                jPanel1.add(scrollPaneWin111, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 80, 340, 310));
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_perfil.png"))); // NOI18N
                jButton1.setBorder(null);
                jButton1.setContentAreaFilled(false);
                jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 21, -1, -1));

                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_agregar.png"))); // NOI18N
                jButton2.setBorder(null);
                jButton2.setContentAreaFilled(false);
                jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jButton2MouseClicked(evt);
                    }
                });
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });
                jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_menu.png"))); // NOI18N
                jButton3.setBorder(null);
                jButton3.setContentAreaFilled(false);
                jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 33, -1, -1));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/txt_refri.png"))); // NOI18N
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 22, -1, -1));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/icn_ingrediente_refri.png"))); // NOI18N
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 87, -1, -1));

                jLabel6.setText("gggg");
                jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/txt_cantidad_refri.png"))); // NOI18N
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 104, -1, -1));

                jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_editar.png"))); // NOI18N
                jButton5.setBorder(null);
                jButton5.setContentAreaFilled(false);
                jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 91, -1, -1));

                jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_eliminiar.png"))); // NOI18N
                jButton6.setBorder(null);
                jButton6.setContentAreaFilled(false);
                jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 89, -1, -1));

                jLabel7.setText("jLabel7");
                jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/txt_ingrediente_refri.png"))); // NOI18N
                jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 88, -1, -1));

                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/fondo.png"))); // NOI18N
                jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 41, -1, -1));

                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/BT_salir_tache.png"))); // NOI18N
                jButton4.setBorder(null);
                jButton4.setContentAreaFilled(false);
                jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jButton4MouseClicked(evt);
                    }
                });
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                    }
                });
                jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 3, 30, 30));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                pack();
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Interfaz_Nuevo_Ingrediente obj = new Interfaz_Nuevo_Ingrediente();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Refrigerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Refrigerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Refrigerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Refrigerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Refrigerador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private final Interfaces.Panel_Lista listPanel = new Interfaces.Panel_Lista();
    private raven.scroll.win11.ScrollPaneWin11 scrollPaneWin111;
    // End of variables declaration//GEN-END:variables
}
