/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author nisit
 */
public class Interfaz_Cambiar_Plan extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Cambiar_Plan
     */
    public Interfaz_Cambiar_Plan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_Fecha_Opcion = new javax.swing.JLabel();
        Lbl_Porciones_Texto = new javax.swing.JLabel();
        Lbl_Tipo_Opcion = new javax.swing.JLabel();
        Lbl_Cambiar_Plan = new javax.swing.JLabel();
        Lbl_Fecha = new javax.swing.JLabel();
        Lbl_Receta_Opcion = new javax.swing.JLabel();
        Lbl_Porciones = new javax.swing.JLabel();
        Lbl_Receta = new javax.swing.JLabel();
        Lbl_Aceptar = new javax.swing.JLabel();
        Lbl_Tipo = new javax.swing.JLabel();
        Lbl_X = new javax.swing.JLabel();
        Lbl_Rectangulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(111, 150, 98));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_Fecha_Opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Rectangulo_Gris.png"))); // NOI18N
        jPanel1.add(Lbl_Fecha_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 80, -1, -1));

        Lbl_Porciones_Texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Porciones_Texto.png"))); // NOI18N
        jPanel1.add(Lbl_Porciones_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 112, -1, -1));

        Lbl_Tipo_Opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Tipo_Opcion.png"))); // NOI18N
        jPanel1.add(Lbl_Tipo_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 79, -1, -1));

        Lbl_Cambiar_Plan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Cambiar_Plan.png"))); // NOI18N
        jPanel1.add(Lbl_Cambiar_Plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 17, -1, -1));

        Lbl_Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Fecha.png"))); // NOI18N
        jPanel1.add(Lbl_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 64, 47, -1));

        Lbl_Receta_Opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Receta_Opcion.png"))); // NOI18N
        jPanel1.add(Lbl_Receta_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 79, -1, -1));

        Lbl_Porciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Porciones.png"))); // NOI18N
        jPanel1.add(Lbl_Porciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 98, -1, -1));

        Lbl_Receta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Receta.png"))); // NOI18N
        jPanel1.add(Lbl_Receta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 64, -1, -1));

        Lbl_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Aceptar.png"))); // NOI18N
        jPanel1.add(Lbl_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 126, -1, -1));

        Lbl_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Tipo.png"))); // NOI18N
        jPanel1.add(Lbl_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 64, 46, -1));

        Lbl_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_X.png"))); // NOI18N
        Lbl_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_XMouseClicked(evt);
            }
        });
        jPanel1.add(Lbl_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 44, -1, -1));

        Lbl_Rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Rectangulo_Claro.png"))); // NOI18N
        jPanel1.add(Lbl_Rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 34, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Lbl_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_XMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Lbl_XMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cambiar_Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cambiar_Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cambiar_Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cambiar_Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Cambiar_Plan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Aceptar;
    private javax.swing.JLabel Lbl_Cambiar_Plan;
    private javax.swing.JLabel Lbl_Fecha;
    private javax.swing.JLabel Lbl_Fecha_Opcion;
    private javax.swing.JLabel Lbl_Porciones;
    private javax.swing.JLabel Lbl_Porciones_Texto;
    private javax.swing.JLabel Lbl_Receta;
    private javax.swing.JLabel Lbl_Receta_Opcion;
    private javax.swing.JLabel Lbl_Rectangulo;
    private javax.swing.JLabel Lbl_Tipo;
    private javax.swing.JLabel Lbl_Tipo_Opcion;
    private javax.swing.JLabel Lbl_X;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
