/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author nisit
 */
public class Interfaz_Editar_Receta extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Editar_Receta
     */
    public Interfaz_Editar_Receta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt_Nombre_Receta = new javax.swing.JLabel();
        Lbl_Porciones = new javax.swing.JLabel();
        Lbl_Receta = new javax.swing.JLabel();
        Lbl_X = new javax.swing.JLabel();
        Lbl_Huevos = new javax.swing.JLabel();
        Lbl_Mas1 = new javax.swing.JLabel();
        Lbl_Huevos_Cuadrado = new javax.swing.JLabel();
        Lbl_Ingredientes = new javax.swing.JLabel();
        Lbl_Procedimiento = new javax.swing.JLabel();
        Lbl_Procedimiento_Rectangulo = new javax.swing.JLabel();
        Lbl_Mas = new javax.swing.JLabel();
        Lbl_Menos = new javax.swing.JLabel();
        Lbl_Ingredientes_Rectangulo = new javax.swing.JLabel();
        Lbl_Tipo = new javax.swing.JLabel();
        Lbl_Tipo_Opcion = new javax.swing.JLabel();
        Lbl_Porciones1 = new javax.swing.JLabel();
        Lbl_Porciones_Texto = new javax.swing.JLabel();
        Lbl_Aceptar = new javax.swing.JLabel();
        Lbl_Rectangulo_Claro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(111, 150, 98));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_Nombre_Receta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Txt_Nombre_Receta.setText("Nombre de la Receta");
        jPanel1.add(Txt_Nombre_Receta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, -1, -1));

        Lbl_Porciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Porciones.png"))); // NOI18N
        jPanel1.add(Lbl_Porciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 54, -1, -1));

        Lbl_Receta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Receta.png"))); // NOI18N
        jPanel1.add(Lbl_Receta, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 23, -1, -1));

        Lbl_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_X.png"))); // NOI18N
        Lbl_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_XMouseClicked(evt);
            }
        });
        jPanel1.add(Lbl_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 41, -1, -1));

        Lbl_Huevos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Huevos.png"))); // NOI18N
        jPanel1.add(Lbl_Huevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 108, -1, -1));

        Lbl_Mas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Mas.png"))); // NOI18N
        jPanel1.add(Lbl_Mas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        Lbl_Huevos_Cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Huevos_Cuadrado.png"))); // NOI18N
        jPanel1.add(Lbl_Huevos_Cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 96, -1, -1));

        Lbl_Ingredientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Ingredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Ingredientes.png"))); // NOI18N
        jPanel1.add(Lbl_Ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 76, 63, 14));

        Lbl_Procedimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Procedimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Procedimiento.png"))); // NOI18N
        jPanel1.add(Lbl_Procedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 198, 76, 21));

        Lbl_Procedimiento_Rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Procedimiento_Rectangulo.png"))); // NOI18N
        jPanel1.add(Lbl_Procedimiento_Rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 221, -1, -1));

        Lbl_Mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Mas.png"))); // NOI18N
        jPanel1.add(Lbl_Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        Lbl_Menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Menos.png"))); // NOI18N
        jPanel1.add(Lbl_Menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 113, -1, -1));
        this.setVisible(false);

        Lbl_Ingredientes_Rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Ingredientes_Rectangulo.png"))); // NOI18N
        jPanel1.add(Lbl_Ingredientes_Rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 96, -1, -1));

        Lbl_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Tipo.png"))); // NOI18N
        jPanel1.add(Lbl_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 331, 79, 20));

        Lbl_Tipo_Opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Tipo_Opcion.png"))); // NOI18N
        jPanel1.add(Lbl_Tipo_Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        Lbl_Porciones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Porciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Nuevo_Plan_Cambiar_Plan/Img_Porciones.png"))); // NOI18N
        jPanel1.add(Lbl_Porciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 331, 79, 20));

        Lbl_Porciones_Texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Porciones_Texto.png"))); // NOI18N
        jPanel1.add(Lbl_Porciones_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 330, -1, -1));

        Lbl_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ingredientes/Img_Aceptar.png"))); // NOI18N
        Lbl_Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_AceptarMouseClicked(evt);
            }
        });
        jPanel1.add(Lbl_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 363, -1, -1));

        Lbl_Rectangulo_Claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Editar_Receta/Img_Rectangulo_Claro.png"))); // NOI18N
        jPanel1.add(Lbl_Rectangulo_Claro, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 35, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Lbl_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_XMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Lbl_XMouseClicked

    private void Lbl_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_AceptarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Lbl_AceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Editar_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Editar_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Editar_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Editar_Receta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Editar_Receta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Aceptar;
    private javax.swing.JLabel Lbl_Huevos;
    private javax.swing.JLabel Lbl_Huevos_Cuadrado;
    private javax.swing.JLabel Lbl_Ingredientes;
    private javax.swing.JLabel Lbl_Ingredientes_Rectangulo;
    private javax.swing.JLabel Lbl_Mas;
    private javax.swing.JLabel Lbl_Mas1;
    private javax.swing.JLabel Lbl_Menos;
    private javax.swing.JLabel Lbl_Porciones;
    private javax.swing.JLabel Lbl_Porciones1;
    private javax.swing.JLabel Lbl_Porciones_Texto;
    private javax.swing.JLabel Lbl_Procedimiento;
    private javax.swing.JLabel Lbl_Procedimiento_Rectangulo;
    private javax.swing.JLabel Lbl_Receta;
    private javax.swing.JLabel Lbl_Rectangulo_Claro;
    private javax.swing.JLabel Lbl_Tipo;
    private javax.swing.JLabel Lbl_Tipo_Opcion;
    private javax.swing.JLabel Lbl_X;
    private javax.swing.JLabel Txt_Nombre_Receta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
