/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author nisit
 */
public class Panel_Opcion extends javax.swing.JPanel {

    public int tipo;
    public String nombre;
    public String Cantidad;
    /**
     * Creates new form NewJPanel
     */
    public Panel_Opcion (int tipo) {
        tipo = this.tipo;
        this.nombre = "Nombre "+tipo;
        this.Cantidad = "3/4 kg";
        initComponents();
        
    }
    public Panel_Opcion(int tipo, String nombre, String Cantidad) {
        tipo = this.tipo;
        nombre = this.nombre;
        Cantidad = this.Cantidad;
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        LblReceta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        LblIngrediente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 255, 206));
        setMaximumSize(new java.awt.Dimension(340, 50));
        setMinimumSize(new java.awt.Dimension(340, 50));
        setPreferredSize(new java.awt.Dimension(340, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("TTT");
        jLabel6.setText(this.Cantidad);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 21, 50, 30));

        jLabel7.setText("jLabel7");
        jLabel7.setText(this.nombre);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 6, 210, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/txt_cantidad_refri.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 21, -1, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_editar.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, -1, -1));

        LblReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/icn_receta_recetario.png"))); // NOI18N
        this.setVisible(false);
        if (this.tipo == 1) {
            this.setVisible(true);
        }
        add(LblReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/txt_ingrediente_refri.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 12, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/bt_eliminiar.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 14, -1, -1));

        LblIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_rec_ref/icn_ingrediente_refri.png"))); // NOI18N
        this.setVisible(false);
        if (this.tipo == 0) {
            this.setVisible(true);
        }
        add(LblIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Interfaz_Editar_Receta obj = new Interfaz_Editar_Receta();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblIngrediente;
    private javax.swing.JLabel LblReceta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
